### PR TITLE
Meetup 35 - February

### PR DESCRIPTION
**Pull request by petros**
- [x] Find a date and a place
- [x] Create a file named YYYYMMDD-meetup-NN in the meetups directory
- [x] Fill in a nice title
- [x] Fill in a summary of the presentation
- [x] Fill in the name of the speaker as a link to their GitHub account
- [x] Fill in a short biography of the speaker
- [x] Add references to resources about the main topic of the presentation under "Notes" as a bullet list
- [x] Prepare video announcement
- [x] Create the meetup.com event
- [x] Create the facebook event
- [x] Add the links here
- [x] When all above are checked off, merge this
- [ ] Create a git.io URL with code thessrb-NN to the permanent link of this file
- [ ] Add event to [SKGTech Calendar](http://skgtech.io/submit-event/)
- [ ] Go crazy announcing the meetup everywhere

### CODE REVIEW

**Comment by petros** [comment]
@eleftherakis could we book a room for Wednesday 18th February?

**Comment by eleftherakis** [comment]
Petro no January? I will check tomorrow that I will be in the office for
Feb. But tell me which date you want for January.

George

**Comment by petros** [comment]
Just for posterity—you have already figured it out—we are probably co-organizing the January one with the Java group.

**Comment by eleftherakis** [comment]
Petro the auditorium is not available, but the  MP room (5th floor the one
we were using in the past) is available and I booked it.

George

**Comment by petros** [comment]
@eleftherakis great! Thanks for doing that! Just to confirm, did you book it for Wednesday 18th?

**Comment by petros** [comment]
@xarisd you said something last Friday about what the subject will be. Do you have more details about that?

**Comment by eleftherakis** [comment]
yes, 7-9. Just be careful because the Psychology dept has a seminar at 8 in
the auditorium, so probably some people will probably attempt to join the
wrong room, but I am sure immdiately they will notice the difference :)

**Comment by xarisd** [comment]
@petros for the February meetup @damphyr will be in Thessaloniki and we agreed that he would present `Rake` and `Capistrano` but I have no confirmation about that.

Otherwise @kootoopas (Fotis Koutoupas) will present `Shoes` (but he has to be notified for this on time).

So I propose to ask @damphyr if he will be here AND can do the presentation and after that @kootoopas.

**Comment by petros** [comment]
Thanks @xarisd 

> will be in Thessaloniki and we agreed that he would present Rake and Capistrano but I have no confirmation about that.

@damphyr consider yourself asked :grin: 

Thanks @eleftherakis! I will put some A4s that will guide people.

**Comment by damphyr** [comment]
Do you want me to do a full presentation or just a quickie 101 for 15 mins?

For a full presentation I would probably add a bit of capistrano 101 on top of rake, otherwise it will be all rake.

**Comment by petros** [comment]
@damphyr my guess is the full presentation, but no more than 60 minutes. You could do less than 60 if it suits you. I am thinking the normal schedule, with me starting with a rubyzino, and you continuing with the presentation. That's *if* you have the time, and *energy* to prepare something. If not, no problem. Just let me know, and we can go with the next alternative. :smile:

**Comment by damphyr** [comment]
Oh but I have it already prepared :) I'll do it. Time I indulged myself once again :)

**Comment by petros** [comment]
Great! Could you share a title and a small summary?

**Comment by damphyr** [comment]
Rake 101:
An introduction to Ruby's favorite build system.
We will take a look and the basic DSL offered by rake, some working examples alongside some lessons learned from using rake to build everything from gems to embedded C/C++ systems.
If time allows we will delve into extending the provided DSL and check how this was done for Capistrano v3

**Pull request merged**
