### PR TITLE
Meetup 36 - March

### PR DESCRIPTION
**Pull request by petros**
Prepare the announcement:

- [x] Find a date and a place
- [x] Rename `meetup-36.md` to `YYYYMMDD-meetup-36.md` in the meetups directory
- [x] Fill in a nice title
- [x] Fill in a summary of the presentation
- [x] Fill in the name of the speaker as a link to their GitHub account
- [x] Fill in a short biography of the speaker
- [x] Add references to resources about the main topic of the presentation under "Notes" as a bullet list
- [ ] Prepare video announcement
- [x] Create the meetup.com event
- [x] Create the facebook event
- [x] Add the links here
- [x] When all above are checked off, merge this
- [ ] Create a git.io URL with code thessrb-NN to the permanent link of `YYYYMMDD-meetup-36.md`
- [ ] Add event to [SKGTech Calendar](http://skgtech.io/submit-event/)
- [ ] Go crazy announcing the meetup everywhere

### CODE REVIEW

**Comment by petros** [comment]
@eleftherakis could we reserve a room for 2015-03-27 (Friday)?

**Comment by petros** [comment]
@gmanolis any chance you could do a presentation on ActiveRecord on 2015-03-27?

**Comment by gmanolis** [comment]
@petros fine by me

**Comment by petros** [comment]
@gmanolis great thanks!!! We still need to get a confirmation from @eleftherakis on the date, but in the meantime if you could share a title, a summary, and a very short biography, it would be swell!

**Comment by gmanolis** [comment]
Ok

**Comment by eleftherakis** [comment]
MP Room 5th floor is booked 7-9 pm.

**Comment by petros** [comment]
Thanks @eleftherakis!

**Comment by petros** [comment]
@thanpolas could you add the event to the SKG calendar? :smile:

**Pull request merged**
