### PR TITLE
Meetup 34 - January

### PR DESCRIPTION
**Pull request by petros**
- [x] Find a date and a place
- [x] Create a file named YYYYMMDD-meetup-NN in the meetups directory
- [x] Fill in a nice title
- [x] Fill in a summary of the presentation
- [x] Fill in the name of the speaker as a link to their GitHub account
- [x] Fill in a short biography of the speaker
- [ ] Add references to resources about the main topic of the presentation under "Notes" as a bullet list
- [ ] Prepare video announcement
- [x] Create the meetup.com event
- [x] Create the facebook event
- [x] Add the links here
- [ ] When all above are checked off, merge this
- [ ] Create a git.io URL with code thessrb-NN to the permanent link of this file
- [ ] Add event to [SKGTech Calendar](http://skgtech.io/submit-event/)
- [ ] Go crazy announcing the meetup everywhere

### CODE REVIEW

**Comment by Drakevr** [comment]
Can we do it on Tu 13th instead?

**Comment by petros** [comment]
@Drakevr would 23th be better for you? There is a small chance of co-organizing something with the Java group that day.

**Comment by petros** [comment]
@Drakevr also, let me know if 21st would also do.

**Comment by Drakevr** [comment]
issue is: i need it sooner not later :P
If it's too soon/not possible though i will have to try rearranging
some stuff and be there on the 20th

**Comment by hypest** [comment]
And as @georgiats has mentioned elsewhere, it's better to by-default avoid the 3rd Tue of the month so to not clash with the OpenCoffee meetups...

**Comment by petros** [comment]
I hear you all. I'll try to adapt for future meetups. The January one, however, will probably be a co-organized event with the Java group on 23th. We are still ironing the details. I'll be back with more information. Watch this space.

**Comment by eleftherakis** [comment]
The Java is already settled and will be a hangout. So this answer my
previous question about January too. The room is the auditorium so it fits
us all.

**Comment by petros** [comment]
@xarisd do you agree on co-organizing it? I am gonna start adding more details here once I get the :ok: from you.

**Comment by xarisd** [comment]
Hey guys! 
Sorry for the delayed answer!

@petros  :ok: and :+1:

**Pull request merged**
